/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listServiceTypes"];
        put?: never;
        /** @description Admin only. Adds a claimable service category to the catalogue. */
        post: operations["createServiceType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listContracts"];
        put?: never;
        /** @description Admin only. */
        post: operations["createContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlans"];
        put?: never;
        /** @description Admin only. */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Full version history, newest effective_from first. */
        get: operations["listCoverageRules"];
        put?: never;
        /** @description Admin only. THE config-driven policy change: atomically closes the previous open version for (plan, service type) — clamped on same-day re-publish — inserts the new version, and records a config_change audit entry. Benefits change with no code deploy. */
        post: operations["createCoverageRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Staff (admin, reviewer). */
        get: operations["listEmployees"];
        put?: never;
        /** @description Admin only. */
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Staff, or the employee's own linked account. */
        get: operations["getEmployee"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Admin only. Partial update. */
        patch: operations["updateEmployee"];
        trace?: never;
    };
    "/employees/{id}/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Staff or self. */
        get: operations["listDependents"];
        put?: never;
        /** @description Admin only. */
        post: operations["createDependent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/remaining-caps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Staff or self. One entry per service type with an active rule under the employee's plan; empty when no plan is assigned. */
        get: operations["remainingCaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Employees see only their own claims; staff and auditors see all. */
        get: operations["listClaims"];
        put?: never;
        /** @description Employee (self) or admin (any employee). Creates a draft. */
        post: operations["createClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Owner, staff, or auditor. */
        get: operations["getClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Audit trail of one claim, newest first. */
        get: operations["claimHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Documents attached to a claim. Visible to anyone who may read the claim. */
        get: operations["listClaimAttachments"];
        put?: never;
        /** @description Upload one supporting document. Permitted only for the claim's owner (or an admin) and only while the claim is in draft or has been returned for documents — evidence is frozen once a reviewer takes the claim. Accepted types are sniffed from the content, not the declared type: application/pdf, image/jpeg, image/png, image/webp. Maximum 5 MiB. */
        post: operations["uploadClaimAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/attachments/{attachmentID}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download the stored bytes. Always served as an attachment with X-Content-Type-Options: nosniff, so an uploaded document can never be rendered inline in the browser. */
        get: operations["downloadClaimAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner or admin. draft → submitted. */
        post: operations["submitClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner or admin. returned_for_docs → submitted. */
        post: operations["resubmitClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/start-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff. submitted → under_review. */
        post: operations["startReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff. under_review → approved. Prices the claim against the active coverage rule automatically (percent, per-claim cap, remaining annual cap); the response carries coverage_percent_applied and payable_amount. */
        post: operations["approveClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff. under_review → rejected. Reason is mandatory. */
        post: operations["rejectClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/return-for-docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff. under_review → returned_for_docs. Reason is mandatory. */
        post: operations["returnClaimForDocs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff. approved → paid. Records a simulated payment. */
        post: operations["markClaimPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Staff. rejected | paid → closed. */
        post: operations["closeClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin or auditor. */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin or auditor. */
        get: operations["reportSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/spend-by-employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin or auditor. */
        get: operations["reportSpendByEmployee"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/spend-by-service-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin or auditor. Names prefer the Persian service-type name. */
        get: operations["reportSpendByServiceType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/spend-by-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin or auditor. Buckets by Gregorian YYYY-MM of receipt date. */
        get: operations["reportSpendByMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Admin only. */
        get: operations["listUsers"];
        put?: never;
        /** @description Admin only. Role must be reviewer, employee, or auditor — admin cannot be created via this endpoint (use seed or make create-admin). */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Admin only. Partial update (role / active / password). Cannot promote to admin or demote the existing admin; password and is_active remain allowed. */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/integration/employees/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Parent-system bulk upsert by personnel_no. API-key auth. */
        post: operations["syncEmployees"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/claims/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Minimal claim status view for the parent system. API-key auth. */
        get: operations["integrationClaimStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /** @enum {string} */
        Role: "admin" | "reviewer" | "employee" | "auditor";
        /** @enum {string} */
        AssignableRole: "reviewer" | "employee" | "auditor";
        /** @enum {string} */
        EmploymentStatus: "active" | "terminated";
        /** @enum {string} */
        Relation: "self" | "spouse" | "child" | "parent";
        /** @enum {string} */
        BeneficiaryType: "self" | "dependent";
        /** @enum {string} */
        ClaimStatus: "draft" | "submitted" | "under_review" | "returned_for_docs" | "approved" | "rejected" | "payment_calculated" | "paid" | "closed";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            full_name: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            employee_id: string | null;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Employee: {
            /** Format: uuid */
            id: string;
            personnel_no: string;
            full_name: string;
            national_id: string;
            employment_status: components["schemas"]["EmploymentStatus"];
            /** Format: date-time */
            hire_date: string;
            department: string;
            /** Format: uuid */
            plan_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Dependent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employee_id: string;
            full_name: string;
            relation: components["schemas"]["Relation"];
            national_id: string;
            /** Format: date-time */
            birth_date: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ServiceType: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        InsuranceContract: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            start_date: string;
            /** Format: date-time */
            end_date: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CoveragePlan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            contract_id: string;
            name: string;
            description: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CoverageRule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            plan_id: string;
            /** Format: uuid */
            service_type_id: string;
            coverage_percent: number;
            per_claim_cap: number | null;
            annual_cap: number | null;
            waiting_period_days: number;
            eligible_relations: components["schemas"]["Relation"][];
            /** Format: date-time */
            effective_from: string;
            /** Format: date-time */
            effective_to: string | null;
            /** Format: uuid */
            created_by: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Claim: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employee_id: string;
            beneficiary_type: components["schemas"]["BeneficiaryType"];
            /** Format: uuid */
            dependent_id: string | null;
            /** Format: uuid */
            service_type_id: string;
            /** Format: uuid */
            plan_id: string;
            requested_amount: number;
            /** Format: date-time */
            receipt_date: string;
            description: string;
            status: components["schemas"]["ClaimStatus"];
            coverage_percent_applied: number | null;
            payable_amount: number | null;
            /** @description Present only when a reviewer rejected or returned the claim. */
            rejection_reason?: string;
            /** Format: date-time */
            submitted_at: string | null;
            /** Format: uuid */
            reviewed_by: string | null;
            /** Format: date-time */
            reviewed_at: string | null;
            /** Format: date-time */
            paid_at: string | null;
            /** Format: date-time */
            closed_at: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            entity_type: string;
            entity_id: string;
            action: string;
            /** Format: uuid */
            actor_user_id: string | null;
            actor_username: string;
            before_data: {
                [key: string]: unknown;
            } | null;
            after_data: {
                [key: string]: unknown;
            } | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            occurred_at: string;
        };
        RemainingCap: {
            service_type_code: string;
            service_type_name: string;
            coverage_percent: number;
            per_claim_cap: number | null;
            annual_cap: number | null;
            used_annual: number;
            remaining_annual: number | null;
        };
        ReportSummary: {
            total_claims: number;
            total_paid_amount: number;
            pending_review: number;
            approved_awaiting_payment: number;
            rejected: number;
        };
        EmployeeSpend: {
            /** Format: uuid */
            employee_id: string;
            employee_name: string;
            personnel_no: string;
            total_paid: number;
            claim_count: number;
        };
        ServiceTypeSpend: {
            service_type_code: string;
            service_type_name: string;
            total_paid: number;
            claim_count: number;
        };
        MonthSpend: {
            month: string;
            total_paid: number;
            claim_count: number;
        };
        /** @description A supporting document uploaded against a claim. The on-disk storage key is intentionally not exposed; use download_url to fetch the bytes. */
        Attachment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            claim_id: string;
            /** @description Original file name, sanitised to a plain name. */
            file_name: string;
            /** Format: date-time */
            uploaded_at: string;
            /** @description Path of the download endpoint for this attachment. */
            download_url: string;
        };
        ClaimList: {
            items: components["schemas"]["Claim"][];
            total: number;
        };
        EmployeeList: {
            items: components["schemas"]["Employee"][];
            total: number;
        };
        AuditLogList: {
            items: components["schemas"]["AuditLog"][];
            total: number;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        CreateClaimRequest: {
            /**
             * Format: uuid
             * @description Admins may file for any employee; employees are forced to their own.
             */
            employee_id?: string | null;
            beneficiary_type: components["schemas"]["BeneficiaryType"];
            /** Format: uuid */
            dependent_id?: string | null;
            /** Format: uuid */
            service_type_id: string;
            requested_amount: number;
            /** Format: date-time */
            receipt_date: string;
            description?: string;
        };
        ReasonRequest: {
            reason: string;
        };
        CreateEmployeeRequest: {
            personnel_no: string;
            full_name: string;
            national_id?: string;
            /** Format: date-time */
            hire_date: string;
            department?: string;
            /** Format: uuid */
            plan_id?: string | null;
        };
        UpdateEmployeeRequest: {
            employment_status?: components["schemas"]["EmploymentStatus"];
            /** Format: uuid */
            plan_id?: string | null;
            department?: string;
            full_name?: string;
        };
        CreateDependentRequest: {
            full_name: string;
            relation: components["schemas"]["Relation"];
            national_id?: string;
            /** Format: date-time */
            birth_date?: string | null;
        };
        CreateServiceTypeRequest: {
            /** @description Stable machine code (lowercase, digits, underscores), unique. */
            code: string;
            /** @description Display name (Persian). */
            name: string;
        };
        CreateContractRequest: {
            name: string;
            /** Format: date-time */
            start_date: string;
            /** Format: date-time */
            end_date: string;
            is_active?: boolean;
        };
        CreatePlanRequest: {
            /** Format: uuid */
            contract_id: string;
            name: string;
            description?: string;
        };
        CreateCoverageRuleRequest: {
            /** Format: uuid */
            plan_id: string;
            /** Format: uuid */
            service_type_id: string;
            coverage_percent: number;
            per_claim_cap?: number | null;
            annual_cap?: number | null;
            waiting_period_days?: number;
            eligible_relations: components["schemas"]["Relation"][];
            /** Format: date-time */
            effective_from: string;
        };
        /** @description Creates a non-admin user. Role must be reviewer, employee, or auditor; admin is rejected (403). Bootstrap the sole admin with seed or make create-admin. */
        CreateUserRequest: {
            username: string;
            password: string;
            full_name: string;
            role: components["schemas"]["AssignableRole"];
            /** Format: uuid */
            employee_id?: string | null;
        };
        /** @description Partial update. Cannot set role to admin, and cannot change the existing admin's role away from admin (403). Password and is_active for admin are allowed. */
        UpdateUserRequest: {
            role?: components["schemas"]["AssignableRole"];
            is_active?: boolean;
            password?: string;
        };
        SyncEmployeesRequest: {
            employees: {
                personnel_no: string;
                full_name: string;
                national_id?: string;
                employment_status: components["schemas"]["EmploymentStatus"];
                /** Format: date-time */
                hire_date: string;
                department?: string;
                /** Format: uuid */
                plan_id?: string | null;
            }[];
        };
        SyncEmployeesResponse: {
            created: number;
            updated: number;
        };
        IntegrationClaimStatus: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ClaimStatus"];
            payable_amount: number | null;
        };
    };
    responses: {
        /** @description Error envelope (all non-2xx responses). */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Page: number;
        PageSize: number;
        /** @description Inclusive lower bound, YYYY-MM-DD. */
        FromDate: string;
        /** @description Inclusive upper bound, YYYY-MM-DD. */
        ToDate: string;
        ClaimID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listServiceTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All service types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceType"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createServiceType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceTypeRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceType"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listContracts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All insurance contracts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsuranceContract"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContractRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsuranceContract"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPlans: {
        parameters: {
            query?: {
                contract_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coverage plans. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoveragePlan"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoveragePlan"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCoverageRules: {
        parameters: {
            query?: {
                plan_id?: string;
                service_type_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRule"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCoverageRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCoverageRuleRequest"];
            };
        };
        responses: {
            /** @description The new active rule version. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listEmployees: {
        parameters: {
            query?: {
                /** @description Matches full name or personnel number. */
                q?: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDependents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependents of the employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dependent"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createDependent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDependentRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dependent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    remainingCaps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Remaining annual caps. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemainingCap"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listClaims: {
        parameters: {
            query?: {
                status?: components["schemas"]["ClaimStatus"];
                employee_id?: string;
                service_type_id?: string;
                /** @description Inclusive lower bound, YYYY-MM-DD. */
                from?: components["parameters"]["FromDate"];
                /** @description Inclusive upper bound, YYYY-MM-DD. */
                to?: components["parameters"]["ToDate"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClaimRequest"];
            };
        };
        responses: {
            /** @description The draft claim. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    claimHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLog"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listClaimAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachments, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadClaimAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The stored attachment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    downloadClaimAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
                attachmentID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    submitClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resubmitClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    approveClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The priced, approved claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    rejectClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description The rejected claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    returnClaimForDocs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description The returned claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    markClaimPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The paid claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    closeClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The closed claim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                entity_type?: string;
                entity_id?: string;
                actor_user_id?: string;
                action?: string;
                /** @description Inclusive lower bound, YYYY-MM-DD. */
                from?: components["parameters"]["FromDate"];
                /** @description Inclusive upper bound, YYYY-MM-DD. */
                to?: components["parameters"]["ToDate"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reportSummary: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, YYYY-MM-DD. */
                from?: components["parameters"]["FromDate"];
                /** @description Inclusive upper bound, YYYY-MM-DD. */
                to?: components["parameters"]["ToDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reportSpendByEmployee: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, YYYY-MM-DD. */
                from?: components["parameters"]["FromDate"];
                /** @description Inclusive upper bound, YYYY-MM-DD. */
                to?: components["parameters"]["ToDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Committed spend per employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeSpend"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reportSpendByServiceType: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, YYYY-MM-DD. */
                from?: components["parameters"]["FromDate"];
                /** @description Inclusive upper bound, YYYY-MM-DD. */
                to?: components["parameters"]["ToDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Committed spend per service type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypeSpend"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reportSpendByMonth: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, YYYY-MM-DD. */
                from?: components["parameters"]["FromDate"];
                /** @description Inclusive upper bound, YYYY-MM-DD. */
                to?: components["parameters"]["ToDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Committed spend per month. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthSpend"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    syncEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncEmployeesRequest"];
            };
        };
        responses: {
            /** @description Upsert counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncEmployeesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    integrationClaimStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ClaimID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationClaimStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
