import puppeteer from 'puppeteer-core'
const OUT='/tmp/claude-1000/-home-saeedm-Documents-fp/120c0151-aecc-45c3-8f75-55f4fdb5dae4/scratchpad/devup'
import {mkdirSync} from 'node:fs'; mkdirSync(OUT,{recursive:true})
const wait=ms=>new Promise(r=>setTimeout(r,ms))
const b=await puppeteer.launch({executablePath:'/usr/bin/google-chrome-stable',headless:'new',args:['--no-sandbox','--window-size=1440,1000']})
const p=await b.newPage(); await p.setViewport({width:1440,height:1000})
await p.emulateMediaFeatures([{name:'prefers-color-scheme',value:'light'}])
const errs=[]; p.on('pageerror',e=>errs.push('pageerror: '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text().slice(0,150))})
await p.goto('http://localhost:5173/login',{waitUntil:'networkidle2'})
await p.type('#username','reviewer'); await p.type('#password','Reviewer123!')
await Promise.all([p.waitForNavigation({waitUntil:'networkidle2'}).catch(()=>{}),p.click('button[type=submit]')]); await wait(1200)
await p.screenshot({path:`${OUT}/1-reviewer-queue.png`})
console.log('after login url:', p.url())
console.log('nav items:', await p.evaluate(()=>[...document.querySelectorAll('aside a')].map(a=>a.textContent.trim()).join(' | ')))
// admin: check a lazy-loaded, react-query-migrated page (Plans)
const p2=await (await b.createBrowserContext()).newPage(); await p2.setViewport({width:1440,height:1000})
await p2.emulateMediaFeatures([{name:'prefers-color-scheme',value:'light'}])
p2.on('pageerror',e=>errs.push('admin pageerror: '+e.message))
await p2.goto('http://localhost:5173/login',{waitUntil:'networkidle2'})
await p2.type('#username','admin'); await p2.type('#password','Admin123!')
await Promise.all([p2.waitForNavigation({waitUntil:'networkidle2'}).catch(()=>{}),p2.click('button[type=submit]')]); await wait(800)
await p2.goto('http://localhost:5173/plans',{waitUntil:'networkidle2'}); await wait(1200)
await p2.screenshot({path:`${OUT}/2-admin-plans.png`})
console.log('plans rows:', await p2.evaluate(()=>document.querySelectorAll('tbody tr').length))
await p2.goto('http://localhost:5173/reports',{waitUntil:'networkidle2'}); await wait(1800)
await p2.screenshot({path:`${OUT}/3-admin-reports.png`})
console.log('report tiles:', await p2.evaluate(()=>[...document.querySelectorAll('main .text-2xl')].map(e=>e.textContent.trim()).join(' | ')))
console.log('JS ERRORS:', errs.length? errs.join('\n  '):'none')
await b.close()
