// The information architecture, ordered for three readers in turn: someone
// evaluating the project, someone integrating with it, and someone maintaining
// it. Explicit rather than autogenerated so the order is a decision, and so the
// Markdown in docs/ needs no frontmatter (which GitHub renders as a table).
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['start/the-one-idea', 'start/run-locally', 'start/tour'],
    },
    {
      type: 'category',
      label: 'How it works',
      collapsed: false,
      items: [
        'how-it-works/domain-model',
        'how-it-works/pricing',
        'how-it-works/rule-versioning',
        'how-it-works/claim-lifecycle',
        'how-it-works/documents',
        'how-it-works/audit-trail',
        'how-it-works/permissions',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        { type: 'link', label: 'API reference', href: '/api' },
        'reference/authentication',
        'reference/errors',
        'reference/database',
        'reference/configuration',
        'reference/hr-integration',
      ],
    },
    {
      type: 'category',
      label: 'Engineering',
      items: [
        'engineering/architecture',
        'engineering/decisions',
        'engineering/testing',
        'engineering/ci',
        'engineering/adding-a-feature',
      ],
    },
    {
      type: 'category',
      label: 'About',
      items: ['about/scope', 'about/reuse'],
    },
  ],
}

export default sidebars
